CREATE TABLE SELECTED(
	ORDER_ID CHAR ( 10 ),
	FOOD_ID CHAR ( 10 ),
	CONSTRAINT SELECTED_PK PRIMARY KEY ( ORDER_ID, FOOD_ID ),
	FOREIGN KEY ( ORDER_ID ) REFERENCES "ORDER" ( ID ) ON DELETE CASCADE,
	FOREIGN KEY ( FOOD_ID ) REFERENCES FOOD_ITEM ( ID ) --  ON DELETE ??

);