CREATE TABLE PAYS (
	ORDER_ID CHAR ( 10 ),
	PAY_ID CHAR ( 10 ),
	CONSTRAINT PAYS_PK PRIMARY KEY ( PAY_ID ),
	FOREIGN KEY ( ORDER_ID ) REFERENCES "ORDER" ( ID ) ON DELETE CASCADE,
  FOREIGN KEY ( PAY_ID ) REFERENCES PAYMENT ( ID ) ON DELETE CASCADE 
);