<<<<<<< HEAD:ORACLE/CREATE_TABLE/17.OFFERS.sql
  
CREATE TABLE OFFERS(
          ADMIN_ID CHAR(10) NOT NULL,
					CUSTOMER_ID CHAR(10),
					PROMO_ID CHAR(10),
					CONSTRAINT OFFERS_PK PRIMARY KEY(CUSTOMER_ID,PROMO_ID),
					FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ID) ON DELETE CASCADE,
					FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID) ON DELETE CASCADE,
					FOREIGN KEY(PROMO_ID) REFERENCES PROMO(ID) ON DELETE CASCADE	
);
=======
--DROP TABLE OFFERS;
CREATE TABLE OFFERS(
          ADMIN_ID CHAR(10) NOT NULL,
					CUSTOMER_ID CHAR(10),
					PROMO_ID CHAR(10),
					REMAINING_PROMO INTEGER,
					CONSTRAINT OFFERS_PK PRIMARY KEY(CUSTOMER_ID,PROMO_ID),
					FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ID) ON DELETE CASCADE,
					FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID) ON DELETE CASCADE,
					FOREIGN KEY(PROMO_ID) REFERENCES PROMO(ID) ON DELETE CASCADE	
);
>>>>>>> 9afde92b1b7eced24fc876eab7f7768108a68914:ORACLE/CREATE TABLE/106. OFFERS .sql
