CREATE TABLE DELIVERS(
         ORDER_ID CHAR(10) NOT NULL,
         FOODMAN_ID CHAR(10) NOT NULL,
				 CONSTRAINT DELIVERS_PK PRIMARY KEY(ORDER_ID),
				 FOREIGN KEY(ORDER_ID) REFERENCES "ORDER"(ID) ON DELETE CASCADE,
				 FOREIGN KEY(FOODMAN_ID) REFERENCES FOODMAN(ID) ON DELETE CASCADE
				 
);