CREATE TABLE CUSTOMER (
	ID CHAR(10) NOT NULL,
	LAST_NAME VARCHAR2(50) NOT NULL,
	FIRST_NAME VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(50) UNIQUE NOT NULL,
	PASSWORD_HASH VARCHAR2(100),
	ADDRESS VARCHAR2(200),
	CONSTRAINT CUSTOMER_PK PRIMARY KEY ( ID )
);

CREATE TABLE CUSTOMER_PHONE (
	CUSTOMER_ID CHAR ( 10 ),
	PHONE_NO VARCHAR2 ( 15 ),
	CONSTRAINT CUSTOMER_PHONE_PK PRIMARY KEY ( CUSTOMER_ID, PHONE_NO ),
  CONSTRAINT CUSTOMER_PHONE_FK FOREIGN KEY ( CUSTOMER_ID ) REFERENCES CUSTOMER ( ID ) ON DELETE CASCADE
);
