CREATE TABLE MANAGES (
	RESTUARANT_ID CHAR ( 5 ),
	ADMIN_ID CHAR ( 5 ),
	CONSTRAINT MANAGES_PK PRIMARY KEY ( RESTUARANT_ID ),
CONSTRAINT MANAGES_RESTUARANT_FK FOREIGN KEY ( RESTUARANT_ID ) REFERENCES RESTUARANT ( ID ) ON DELETE CASCADE,CONSTRAINT MANAGES_ADMIN_FK FOREIGN KEY ( ADMIN_ID ) REFERENCES ADMIN ( ID ) ON DELETE SET NULL
);