CREATE TABLE MANAGES(
        RESTAURANT_ID CHAR(10) NOT NULL,
				ADMIN_ID CHAR(10) NOT NULL,
				CONSTRAINT MANAGES_PK PRIMARY KEY(RESTAURANT_ID),
				FOREIGN KEY(RESTAURANT_ID) REFERENCES RESTAURANT(ID) ON DELETE CASCADE,
				FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ID) ON DELETE SET NULL
);
