CREATE TABLE CHOOSES (
	ORDER_ID CHAR( 10 ),
	CUSTOMER_ID CHAR( 10 ),
	CONSTRAINT CHOOSES_PK PRIMARY KEY ( ORDER_ID ),
	CONSTRAINT CHOOSES_ORDER_FK FOREIGN_KEY ( ORDER_ID ) REFERENCES ORDER ( ID ) ON DELETE CASCADE,
CONSTRAINT CHOOSES_CUSTOMER_FK FOREIGN_KEY ( CUSTOMER_ID ) REFERENCES CUSTOMER ( ID ) ON DELETE CASCADE 
);