CREATE TABLE CHOOSES (
         ORDER_ID CHAR(10),
				 CUSTOMER_ID CHAR(10),
				 CONSTRAINT CHOOSES_PK PRIMARY KEY(ORDER_ID),
				 FOREIGN KEY(ORDER_ID) REFERENCES "ORDER"(ID) ON DELETE CASCADE,
				 FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID) ON DELETE CASCADE
);
