CREATE TABLE OFFERS (
	ADMIN_ID CHAR ( 5 ) NOT NULL,
	CUSTOMER_ID CHAR ( 5 ),
	PROMO_ID CHAR ( 5 ),
	REMAINING PROMO NUMBER,
	CONSTRAINT OFFERS_PK PRIMARY KEY ( CUSTOMER_ID, PROMO_ID ),
	CONSTRAINT OFFERS_ADMIN_FK FOREIGN KEY ( ADMIN_ID ) REFERENCES ADMIN ( ID ) -- ON DELETE ???
	CONSTRAINT OFFERS_CUSTOMER_FK FOREIGN KEY ( CUSTOMER_ID ) REFERENCES CUSTOMER ( ID ) ON DELETE CASCADE,
CONSTRAINT OFFERS_PROMO_FK FOREIGN KEY ( PROMO_ID ) REFERENCES PROMO ( ID ) ON DELETE CASCADE 
);