--DROP TABLE ADMIN_PHONE;

CREATE TABLE ADMIN_PHONE (
	ADMIN_ID VARCHAR2 ( 15 ),
	PHONE_NO VARCHAR2 ( 15 ),
	CONSTRAINT ADMIN_PHONE_PK PRIMARY KEY ( ADMIN_ID, PHONE_NO ),
CONSTRAINT ADMIN_PHONE_FK FOREIGN KEY ( ADMIN_ID ) REFERENCES ADMIN ( ID ) ON DELETE CASCADE 
);