CREATE TABLE FOOD_ITEM_PATH (
	FOOD_ID VARCHAR2 ( 15 ),
	IMAGE_PATH VARCHAR2 ( 200 ),
	CONSTRAINT FOOD_ITEM_PATH_PK PRIMARY KEY ( FOOD_ID, IMAGE_PATH ),
CONSTRAINT FOOD_ITEM_PATH_FK FOREIGN KEY ( FOOD_ID ) REFERENCES FOOD_ITEM ( ID ) 
);