-- DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER 
(
	ID VARCHAR2(15),
	LAST_NAME VARCHAR2(50) NOT NULL,
	FIRST_NAME VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(50) UNIQUE NOT NULL,
	PASSWORD_HASH VARCHAR2(200),
	ADDRESS VARCHAR2(200),
	CONSTRAINT CUSTOMER_PK PRIMARY KEY ( ID )
)