CREATE TABLE APPOINTS(
         FOODMAN_ID CHAR(10) NOT NULL,
				 CONTRACT_ID CHAR(10) NOT NULL,
				 ADMIN_ID CHAR(10) NOT NULL,
				 CONSTRAINT APPOINTS_PK PRIMARY KEY(FOODMAN_ID,CONTRACT_ID),
				 FOREIGN KEY(FOODMAN_ID) REFERENCES FOODMAN(ID) ON DELETE CASCADE,
				 FOREIGN KEY(CONTRACT_ID) REFERENCES CONTRACT(ID) ON DELETE CASCADE,
				 FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ID) ON DELETE CASCADE
);