CREATE TABLE CONTRACT(
             CONTRACT_ID CHAR(10) NOT NULL,
						 FOODMAN_ID CHAR(10) NOT NULL,
						 DURATION INTEGER,
						 SALARY FLOAT NOT NULL,
						 INIT_RATING INTEGER CHECK (INIT_RATING BETWEEN 0 AND 5),
						 DATE_OF_CONTRACT DATE,
						 CONSTRAINT CONTRACT_PK PRIMARY KEY(CONTRACT_ID),
					   FOREIGN KEY(FOODMAN_ID) REFERENCES FOODMAN(FOODMAN_ID)	
);