--DROP TABLE CUSTOMER;


CREATE TABLE CUSTOMER (
	ID CHAR(10) NOT NULL,
	LAST_NAME VARCHAR2(50) NOT NULL,
	FIRST_NAME VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(50) UNIQUE NOT NULL,
	PASSWORD_HASH VARCHAR2(100),
	ADDRESS VARCHAR2(200),
	CONSTRAINT CUSTOMER_PK PRIMARY KEY ( ID )
);

CREATE TABLE CUSTOMER_PHONE (
	CUSTOMER_ID CHAR ( 10 ),
	PHONE_NO VARCHAR2 ( 15 ),
	CONSTRAINT CUSTOMER_PHONE_PK PRIMARY KEY ( CUSTOMER_ID, PHONE_NO ),
CONSTRAINT CUSTOMER_PHONE_FK FOREIGN KEY ( CUSTOMER_ID ) REFERENCES CUSTOMER ( ID ) ON DELETE CASCADE 
);

-- INSERT INTO CUSTOMER ( CUSTNO, CUSTNAME, ADDRESS, INTERNAL, CONTACT, PHONE, CITY, STATE, ZIP )
-- VALUES
-- 	( 'C100', 'Football', 'Box 352200', 'Y', 'Mary Manager', '6857100', 'Boulder', 'CO', '80309' );
-- INSERT INTO CUSTOMER ( CUSTNO, CUSTNAME, ADDRESS, INTERNAL, CONTACT, PHONE, CITY, STATE, ZIP )
-- VALUES
-- 	( 'C101', 'Men''s Basketball', 'Box 352400', 'Y', 'Sally Supervisor', '5431700', 'Boulder', 'CO', '80309' );
-- INSERT INTO CUSTOMER ( CUSTNO, CUSTNAME, ADDRESS, INTERNAL, CONTACT, PHONE, CITY, STATE, ZIP )
-- VALUES
-- 	( 'C103', 'Baseball', 'Box 352020', 'Y', 'Bill Baseball', '5431234', 'Boulder', 'CO', '80309' );
-- INSERT INTO CUSTOMER ( CUSTNO, CUSTNAME, ADDRESS, INTERNAL, CONTACT, PHONE, CITY, STATE, ZIP )
-- VALUES
-- 	( 'C104', 'Women''s Softball', 'Box 351200', 'Y', 'Sue Softball', '5434321', 'Boulder', 'CO', '80309' );
-- INSERT INTO CUSTOMER ( CUSTNO, CUSTNAME, ADDRESS, INTERNAL, CONTACT, PHONE, CITY, STATE, ZIP )
-- VALUES
	