
CREATE TABLE FOOD_ITEM (
	ID CHAR ( 10 ) UNIQUE,
	RESTAURANT_ID CHAR(10) NOT NULL,
	NAME VARCHAR2 ( 50 ) NOT NULL,
	PRICE INTEGER NOT NULL,
	OFFER INTEGER,
	AVAILIBILITY CHAR ( 1 ),
	DESCRIPTION VARCHAR2 ( 1000 ),
	"TYPE" VARCHAR2 ( 50 ),
	CONSTRAINT FOOD_ITEM_PK PRIMARY KEY(ID,RESTAURANT_ID),
	FOREIGN KEY(RESTAURANT_ID) REFERENCES RESTAURANT(ID)
		
);