CREATE TABLE FOOD_ITEM (
	ID CHAR ( 10 ) UNIQUE,
	RESTAURANT_ID CHAR ( 10 ) NOT NULL,
	NAME VARCHAR2 ( 50 ) NOT NULL,
	PRICE INTEGER NOT NULL,
	OFFER INTEGER,
	AVAILIBILITY CHAR ( 1 ),
	DESCRIPTION VARCHAR2 ( 1000 ),
	"TYPE" VARCHAR2 ( 50 ),
	CONSTRAINT FOOD_ITEM_PK PRIMARY KEY ( ID, RESTAURANT_ID ),
	FOREIGN KEY ( RESTAURANT_ID ) REFERENCES RESTAURANT ( ID ) 
);
CREATE TABLE FOOD_ITEM_IMAGE (
	FOOD_ID CHAR ( 10 ),
	IMAGE_PATH VARCHAR2 ( 15 ),
	CONSTRAINT FOOD_ITEM_IMAGE_PK PRIMARY KEY ( FOOD_ID, IMAGE_PATH ),
FOREIGN KEY ( FOOD_ID ) REFERENCES FOOD_ITEM ( ID ) ON DELETE CASCADE 
);