CREATE TABLE PAYMENT(
        PAY_ID CHAR(10) NOT NULL,
				ORDER_ID CHAR(10) NOT NULL,
				PAYING_AMOUNT FLOAT NOT NULL,
				PAYMENT_TYPE VARCHAR2(40) NOT NULL,
				DATE_TIME DATE,
				PRIMARY KEY(PAY_ID),
				FOREIGN KEY(ORDER_ID) REFERENCES "ORDER"(ORDER_ID)
);