CREATE TABLE PROMO(
        PROMO_ID CHAR(4) NOT NULL,
				NAME VARCHAR2(30) NOT NULL,
				"PERCENT" INTEGER,
				FIXED_AMOUNT FLOAT NOT NULL,
				PROMO_LIMIT INTEGER NOT NULL,
				MIN_ORDER_VALUE FLOAT NOT NULL,
				MAX_DISCOUNT_AMOUNT FLOAT NOT NULL,
				PRIMARY KEY(PROMO_ID)
);