--DROP TABLE REVIEWS;

CREATE TABLE REVIEWS(
           CUSTOMER_ID CHAR(10) NOT NULL,
					 PAY_ID CHAR(10) NOT NULL,
					 RESTAURANT_ID CHAR(10) NOT NULL,
					 REVIEW_ID CHAR(10) NOT NULL,
					 CONSTRAINT REVIEWS_PK PRIMARY KEY(CUSTOMER_ID,PAY_ID,RESTAURANT_ID),
					 FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID),
					 FOREIGN KEY(PAY_ID) REFERENCES PAYMENT(ID),
					 FOREIGN KEY(RESTAURANT_ID) REFERENCES RESTAURANT(ID),
					 CONSTRAINT REVIEWS_REVIEW_FK FOREIGN KEY(REVIEW_ID) REFERENCES REVIEW(ID) ON DELETE CASCADE
);