CREATE TABLE VEHICLE(
          VEHICLE_ID CHAR(10) NOT NULL,
					FOODMAN_ID CHAR(10) NOT NULL,
					REG_NO CHAR(15) NOT NULL,
					"TYPE" VARCHAR2(50),
					CONSTRAINT VEHICLE_PK PRIMARY KEY(VEHICLE_ID),
					FOREIGN KEY(FOODMAN_ID) REFERENCES FOODMAN(FOODMAN_ID)
);